name: Build Velocity-Whitelist

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@main
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Release Bungeecord-Whitelist
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Bungeecord-Whitelist v1.0"
          automatic_release_tag: "bungee-1.0"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "bungeecord/out"
          prerelease: false
      - name: Release Velocity-Whitelist
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "Velocity-Whitelist v1.0"
          automatic_release_tag: "velocity1.0"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "velocity/out"
          prerelease: false
